scss_files: 'src/styles/partials/**/*.scss'

linters:
    Comment:
        enabled: true
        allowed: '^[/* ]*!'

    EmptyLineBetweenBlocks:
        enabled: false

    HexLength:
        enabled: true
        style: long

    IdSelector:
        enabled: false

    ImportantRule:
        enabled: false

    Indentation:
        enabled: true
        character: space
        width: 4

    LeadingZero:
        enabled: true
        style: include_zero

    MergeableSelector:
        enabled: false

    NestingDepth:
        enabled: false

    PlaceholderInExtend:
        enabled: false

    PropertySortOrder:
        enabled: false

    PseudoElement:
        enabled: false

    QualifyingElement:
        enabled: true
        allow_element_with_attribute: true
        allow_element_with_class: true
        allow_element_with_id: true

    SelectorDepth:
        enabled: false

    StringQuotes:
        enabled: true
        style: single_quotes

    VendorPrefix:
        enabled: false
