# Site settings
title: Forcir Design
email: admin@forcir.com
description: "Style toolkit (framework) and guidelines that power the Forcir Front-End"
baseurl: ""
url: "https://design.forcir.com"
github_username:  Forcir

# Build settings
include: ['_pages']
markdown: kramdown
kramdown:
    input: GFM
